import SwiftUI
import AppKit
import PDFKit

public struct PDFKitRepresentable: NSViewRepresentable {
    let pdfData: Data?
    let zoomScale: CGFloat
    
    public init(pdfData: Data?, zoomScale: CGFloat = 1.0) {
        self.pdfData = pdfData
        self.zoomScale = zoomScale
    }
    
    public func makeCoordinator() -> Coordinator {
        Coordinator()
    }
    
    public func makeNSView(context: Context) -> SmoothPDFContainerView {
        let container = SmoothPDFContainerView()
        container.pdfView.delegate = context.coordinator
        context.coordinator.containerView = container
        container.updateDocument(data: pdfData, zoomScale: zoomScale)
        return container
    }
    
    public func updateNSView(_ container: SmoothPDFContainerView, context: Context) {
        container.pdfView.delegate = context.coordinator
        container.updateDocument(data: pdfData, zoomScale: zoomScale)
    }
    
    public class Coordinator: NSObject, PDFViewDelegate {
        weak var containerView: SmoothPDFContainerView?
        
        public func pdfViewWillClick(onLink sender: PDFView, with url: URL) {
            NSWorkspace.shared.open(url)
        }
    }
}

/// Custom NSImageView that ignores hit-testing so it never interferes with mouse clicks in the underlying PDFView.
private final class NonInteractiveImageView: NSImageView {
    override func hitTest(_ point: NSPoint) -> NSView? {
        nil
    }
}

/// Subclass of PDFView that fixes internal LaTeX / PDF link navigation issues (such as unspecified
/// coordinate values in destinations generated by hyperref / table of contents) and guarantees external URL links open reliably.
public final class ClickablePDFView: PDFView {
    private var pendingAnnotation: PDFAnnotation?
    private var mouseDownLocation: NSPoint?
    private var linkTrackingArea: NSTrackingArea?
    
    public override init(frame frameRect: NSRect) {
        super.init(frame: frameRect)
        setupLinkHandling()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setupLinkHandling()
    }
    
    deinit {
        NotificationCenter.default.removeObserver(self)
    }
    
    private func setupLinkHandling() {
        postsFrameChangedNotifications = true
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(didScrollOrResize),
            name: NSView.boundsDidChangeNotification,
            object: nil
        )
    }
    
    @objc private func didScrollOrResize(_ notification: Notification) {
        window?.invalidateCursorRects(for: self)
    }
    
    public override func updateTrackingAreas() {
        super.updateTrackingAreas()
        if let existing = linkTrackingArea {
            removeTrackingArea(existing)
        }
        let area = NSTrackingArea(
            rect: bounds,
            options: [.mouseMoved, .cursorUpdate, .activeInKeyWindow, .inVisibleRect],
            owner: self,
            userInfo: nil
        )
        addTrackingArea(area)
        linkTrackingArea = area
    }
    
    /// Intercept hit-testing so that clicks on link annotations are routed directly to this view
    /// instead of being swallowed by PDFPageView's internal text selection gesture recognizer.
    public override func hitTest(_ point: NSPoint) -> NSView? {
        let localPoint = superview != nil ? convert(point, from: superview) : point
        if isOverLink(at: localPoint) {
            return self
        }
        return super.hitTest(point)
    }
    
    public func isOverLink(at viewPoint: NSPoint) -> Bool {
        guard let page = page(for: viewPoint, nearest: false) else { return false }
        let pagePoint = convert(viewPoint, to: page)
        return findLinkAnnotation(at: pagePoint, on: page) != nil
    }
    
    public override func cursorUpdate(with event: NSEvent) {
        let viewPoint = convert(event.locationInWindow, from: nil)
        if isOverLink(at: viewPoint) {
            NSCursor.pointingHand.set()
        } else {
            NSCursor.arrow.set()
        }
    }
    
    public override func mouseMoved(with event: NSEvent) {
        let viewPoint = convert(event.locationInWindow, from: nil)
        if let page = page(for: viewPoint, nearest: false) {
            let pagePoint = convert(viewPoint, to: page)
            if let annot = findLinkAnnotation(at: pagePoint, on: page) {
                NSCursor.pointingHand.set()
                updateToolTip(for: annot)
                return
            }
        }
        toolTip = nil
        super.mouseMoved(with: event)
    }
    
    private func updateToolTip(for annotation: PDFAnnotation) {
        if let url = annotation.url ?? (annotation.action as? PDFActionURL)?.url {
            toolTip = url.absoluteString
        } else if let dest = annotation.destination ?? (annotation.action as? PDFActionGoTo)?.destination,
                  let targetPage = dest.page ?? resolvePage(for: dest) {
            let pageNum = targetPage.label ?? "\((document?.index(for: targetPage) ?? -1) + 1)"
            toolTip = String.localizedStringWithFormat(NSLocalizedString("Go to page %@", comment: ""), pageNum)
        } else {
            toolTip = nil
        }
    }
    
    public override func resetCursorRects() {
        super.resetCursorRects()
        discardCursorRects()
        
        guard let doc = document else { return }
        let currentVisible = visibleRect
        
        for pageIndex in 0..<doc.pageCount {
            guard let page = doc.page(at: pageIndex) else { continue }
            let pageBounds = page.bounds(for: displayBox)
            for annotation in page.annotations {
                guard isLink(annotation) else { continue }
                var bounds = annotation.bounds
                if annotation.destination != nil || annotation.action is PDFActionGoTo {
                    // Extend cursor rect across TOC row to cover dots and page numbers
                    let minX = max(pageBounds.minX, bounds.minX - 25)
                    let maxX = max(bounds.maxX, pageBounds.maxX - 50)
                    let minY = bounds.minY - 3
                    let maxY = bounds.maxY + 3
                    bounds = CGRect(x: minX, y: minY, width: maxX - minX, height: maxY - minY)
                }
                let viewRect = convert(bounds, from: page)
                let visibleTarget = viewRect.intersection(currentVisible)
                if !visibleTarget.isEmpty {
                    addCursorRect(visibleTarget, cursor: .pointingHand)
                }
            }
        }
    }
    
    public override func mouseDown(with event: NSEvent) {
        let viewPoint = convert(event.locationInWindow, from: nil)
        
        if let page = page(for: viewPoint, nearest: false) {
            let pagePoint = convert(viewPoint, to: page)
            if let annotation = findLinkAnnotation(at: pagePoint, on: page) {
                pendingAnnotation = annotation
                mouseDownLocation = event.locationInWindow
                return
            }
        }
        
        super.mouseDown(with: event)
    }
    
    public override func mouseUp(with event: NSEvent) {
        let viewPoint = convert(event.locationInWindow, from: nil)
        let downLoc = mouseDownLocation ?? event.locationInWindow
        let distance = hypot(event.locationInWindow.x - downLoc.x, event.locationInWindow.y - downLoc.y)
        
        let targetAnnot: PDFAnnotation? = (distance < 8) ? (pendingAnnotation ?? {
            guard let page = page(for: viewPoint, nearest: false) else { return nil }
            return findLinkAnnotation(at: convert(viewPoint, to: page), on: page)
        }()) : nil
        
        pendingAnnotation = nil
        mouseDownLocation = nil
        
        if let annotation = targetAnnot {
            if handleLink(annotation) {
                return
            }
        }
        
        super.mouseUp(with: event)
    }
    
    public func findLinkAnnotation(at pagePoint: CGPoint, on page: PDFPage) -> PDFAnnotation? {
        // 1. Direct hit-test
        if let annot = page.annotation(at: pagePoint), isLink(annot) {
            return annot
        }
        
        // 2. Tolerance hit-test with margin (6 points)
        for annot in page.annotations.reversed() {
            guard isLink(annot) else { continue }
            if annot.bounds.insetBy(dx: -6, dy: -6).contains(pagePoint) {
                return annot
            }
        }
        
        // 3. Row extension for TOC / index links (internal GoTo or destination):
        // In LaTeX, table of contents entries typically only have annotations around the title text,
        // leaving the leader dots and page numbers without link annotations.
        // We expand the hit area across the entire row so clicking the page number or dots navigates correctly.
        let pageBounds = page.bounds(for: displayBox)
        var bestAnnot: PDFAnnotation? = nil
        var minDistanceY: CGFloat = .infinity
        
        for annot in page.annotations {
            guard annot.destination != nil || annot.action is PDFActionGoTo else { continue }
            let halfHeight = max(annot.bounds.height / 2 + 5, 9)
            let distY = abs(pagePoint.y - annot.bounds.midY)
            if distY <= halfHeight {
                let minX = max(pageBounds.minX, annot.bounds.minX - 30)
                let maxX = max(annot.bounds.maxX, pageBounds.maxX - 50)
                if pagePoint.x >= minX && pagePoint.x <= maxX {
                    if distY < minDistanceY {
                        minDistanceY = distY
                        bestAnnot = annot
                    }
                }
            }
        }
        
        return bestAnnot
    }
    
    public func isLink(_ annotation: PDFAnnotation) -> Bool {
        if let type = annotation.type, type.caseInsensitiveCompare("Link") == .orderedSame || type.caseInsensitiveCompare("/Link") == .orderedSame {
            return true
        }
        return annotation.destination != nil || annotation.action != nil || annotation.url != nil
    }
    
    @discardableResult
    public func handleLink(_ annotation: PDFAnnotation) -> Bool {
        // Direct URL
        if let url = annotation.url {
            openLinkURL(url)
            return true
        }
        
        // Action
        if let action = annotation.action {
            if let gotoAction = action as? PDFActionGoTo {
                goToSanitizedDestination(gotoAction.destination)
                return true
            } else if let urlAction = action as? PDFActionURL, let url = urlAction.url {
                openLinkURL(url)
                return true
            } else if let namedAction = action as? PDFActionNamed {
                switch namedAction.name {
                case .firstPage: goToFirstPage(nil)
                case .lastPage: goToLastPage(nil)
                case .nextPage: goToNextPage(nil)
                case .previousPage: goToPreviousPage(nil)
                case .goBack: goBack(nil)
                case .goForward: goForward(nil)
                default: break
                }
                return true
            } else if let remoteAction = action as? PDFActionRemoteGoTo {
                openLinkURL(remoteAction.url)
                return true
            }
        }
        
        // Direct destination
        if let destination = annotation.destination {
            goToSanitizedDestination(destination)
            return true
        }
        
        return false
    }
    
    private func openLinkURL(_ url: URL) {
        var finalURL = url
        if finalURL.scheme == nil || finalURL.scheme?.isEmpty == true {
            if let withScheme = URL(string: "https://" + finalURL.absoluteString) {
                finalURL = withScheme
            }
        }
        if let delegate = self.delegate {
            delegate.pdfViewWillClick?(onLink: self, with: finalURL)
        } else {
            NSWorkspace.shared.open(finalURL)
        }
    }
    
    public func goToSanitizedDestination(_ destination: PDFDestination) {
        guard let targetPage = destination.page ?? resolvePage(for: destination) else {
            go(to: destination)
            return
        }
        
        let safePoint = Self.sanitizePoint(destination.point, for: targetPage, displayBox: displayBox)
        let safeDestination = PDFDestination(page: targetPage, at: safePoint)
        go(to: safeDestination)
        
        if currentPage != targetPage {
            go(to: targetPage)
        }
    }
    
    public static func sanitizePoint(_ point: CGPoint, for page: PDFPage, displayBox: PDFDisplayBox) -> CGPoint {
        let bounds = page.bounds(for: displayBox)
        var p = point
        
        // Check for unspecified or non-finite X coordinate
        if p.x == kPDFDestinationUnspecifiedValue || !p.x.isFinite || p.x < bounds.minX - 100 || p.x > bounds.maxX + 100 {
            p.x = bounds.minX
        }
        
        // Check for unspecified or non-finite Y coordinate
        if p.y == kPDFDestinationUnspecifiedValue || !p.y.isFinite || p.y < bounds.minY - 100 || p.y > bounds.maxY + 100 {
            p.y = bounds.maxY
        }
        
        // Clamp within page bounds
        p.x = max(bounds.minX, min(bounds.maxX, p.x))
        p.y = max(bounds.minY, min(bounds.maxY, p.y))
        return p
    }
    
    private func resolvePage(for destination: PDFDestination) -> PDFPage? {
        if let page = destination.page { return page }
        if let root = document?.outlineRoot {
            return findPage(in: root, matching: destination)
        }
        return nil
    }
    
    private func findPage(in outline: PDFOutline, matching destination: PDFDestination) -> PDFPage? {
        if let outlineDest = outline.destination, outlineDest == destination {
            return outlineDest.page
        }
        for i in 0..<outline.numberOfChildren {
            if let child = outline.child(at: i) {
                if let page = findPage(in: child, matching: destination) {
                    return page
                }
            }
        }
        return nil
    }
}

/// Custom container view that hosts PDFView and an overlay snapshot view to eliminate any black flash or flickering on recompile.
public final class SmoothPDFContainerView: NSView {
    public let pdfView = ClickablePDFView()
    private let overlayView = NonInteractiveImageView()
    private var lastData: Data? = nil
    private var lastScale: CGFloat = 1.0
    
    override init(frame frameRect: NSRect) {
        super.init(frame: frameRect)
        setup()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }
    
    private func setup() {
        wantsLayer = true
        layerContentsRedrawPolicy = .onSetNeedsDisplay
        layer?.backgroundColor = NSColor.windowBackgroundColor.cgColor
        
        pdfView.displayMode = .singlePageContinuous
        pdfView.displayDirection = .vertical
        pdfView.displaysPageBreaks = true
        pdfView.backgroundColor = NSColor.windowBackgroundColor
        pdfView.wantsLayer = true
        pdfView.layerContentsRedrawPolicy = .onSetNeedsDisplay
        pdfView.layer?.drawsAsynchronously = true
        
        overlayView.imageScaling = .scaleAxesIndependently
        overlayView.isHidden = true
        overlayView.wantsLayer = true
        
        addSubview(pdfView)
        addSubview(overlayView)
    }
    
    public override func layout() {
        super.layout()
        if pdfView.frame != bounds {
            pdfView.frame = bounds
        }
        if overlayView.isHidden && overlayView.frame != bounds {
            overlayView.frame = bounds
        }
    }
    
    public func updateDocument(data: Data?, zoomScale: CGFloat) {
        guard let data = data, !data.isEmpty else {
            pdfView.document = nil
            overlayView.isHidden = true
            lastData = nil
            return
        }
        
        // If data hasn't changed, only update zoom scale if necessary
        if lastData == data {
            applyScale(zoomScale)
            return
        }
        
        // 1. Take snapshot of current view before swapping document to prevent any black frame
        if pdfView.document != nil && bounds.width > 0 && bounds.height > 0 {
            if let rep = pdfView.bitmapImageRepForCachingDisplay(in: bounds) {
                pdfView.cacheDisplay(in: bounds, to: rep)
                let snapshot = NSImage(size: bounds.size)
                snapshot.addRepresentation(rep)
                overlayView.image = snapshot
                overlayView.frame = bounds
                overlayView.alphaValue = 1.0
                overlayView.isHidden = false
            }
        }
        
        lastData = data
        
        guard let newDoc = PDFDocument(data: data) else {
            overlayView.isHidden = true
            return
        }
        
        // Sanitize link annotations on the new document to ensure PDFKit's internal navigators
        // also receive valid coordinates without kPDFDestinationUnspecifiedValue.
        Self.sanitizeAnnotations(in: newDoc, displayBox: pdfView.displayBox)
        
        CATransaction.begin()
        CATransaction.setDisableActions(true)
        
        // Save destination & page index
        let currentDest = pdfView.currentDestination
        let currentPage = pdfView.currentPage
        let pageIndex = currentPage != nil ? (pdfView.document?.index(for: currentPage!) ?? 0) : 0
        
        // Swap document in-place
        pdfView.document = newDoc
        applyScale(zoomScale)
        
        // Restore destination or page so scroll position stays locked
        if let dest = currentDest, let page = dest.page {
            let idx = newDoc.index(for: page)
            let safeIdx = (idx != NSNotFound && idx < newDoc.pageCount) ? idx : 0
            if let targetPage = newDoc.page(at: safeIdx) {
                let safePoint = ClickablePDFView.sanitizePoint(dest.point, for: targetPage, displayBox: pdfView.displayBox)
                pdfView.go(to: PDFDestination(page: targetPage, at: safePoint))
            }
        } else if let targetPage = newDoc.page(at: min(pageIndex, newDoc.pageCount - 1)) {
            pdfView.go(to: targetPage)
        }
        
        CATransaction.commit()
        
        // 2. Smoothly fade out overlay once the new document has drawn its pages
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) { [weak self] in
            guard let self = self else { return }
            NSAnimationContext.runAnimationGroup({ context in
                context.duration = 0.06
                self.overlayView.animator().alphaValue = 0.0
            }, completionHandler: {
                self.overlayView.isHidden = true
                self.overlayView.alphaValue = 1.0
                self.overlayView.image = nil
            })
        }
    }
    
    private static func sanitizeAnnotations(in document: PDFDocument, displayBox: PDFDisplayBox) {
        for pageIndex in 0..<document.pageCount {
            guard let page = document.page(at: pageIndex) else { continue }
            for annot in page.annotations {
                if let gotoAction = annot.action as? PDFActionGoTo {
                    let dest = gotoAction.destination
                    if let targetPage = dest.page {
                        let safePoint = ClickablePDFView.sanitizePoint(dest.point, for: targetPage, displayBox: displayBox)
                        let safeDest = PDFDestination(page: targetPage, at: safePoint)
                        annot.action = PDFActionGoTo(destination: safeDest)
                        annot.destination = safeDest
                    }
                } else if let dest = annot.destination, let targetPage = dest.page {
                    let safePoint = ClickablePDFView.sanitizePoint(dest.point, for: targetPage, displayBox: displayBox)
                    annot.destination = PDFDestination(page: targetPage, at: safePoint)
                }
            }
        }
    }
    
    private func applyScale(_ scale: CGFloat) {
        guard scale != lastScale else { return }
        lastScale = scale
        
        if scale > 0 {
            if pdfView.autoScales {
                pdfView.autoScales = false
            }
            if abs(pdfView.scaleFactor - scale) > 0.001 {
                pdfView.scaleFactor = scale
            }
        } else {
            pdfView.autoScales = true
        }
    }
}

